-- MySQL Script generated by MySQL Workbench
-- Tue Aug 22 19:34:41 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- Criando banco dados
CREATE SCHEMA IF NOT EXISTS `mylibrary` DEFAULT CHARACTER SET utf8 ;


-- Selecionando o banco de dados que iremos utilizar
USE `mylibrary` ;


-- Criando a tabela "author"
CREATE TABLE IF NOT EXISTS `mylibrary`.`author` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(250) NOT NULL,
  `country` VARCHAR(100) NOT NULL,
  `birthday` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- Criando a tabela "book"
CREATE TABLE IF NOT EXISTS `mylibrary`.`book` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(250) NOT NULL,
  `year` INT NOT NULL,
  `genre` VARCHAR(100) NOT NULL,
  `pages` INT NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  `read` TINYINT NOT NULL,
  `rating` INT NULL,
  `author_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_book_author_idx` (`author_id` ASC) VISIBLE,
  CONSTRAINT `fk_book_author`
    FOREIGN KEY (`author_id`)
    REFERENCES `mylibrary`.`author` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- Criando a tabela "loan"
CREATE TABLE IF NOT EXISTS `mylibrary`.`loan` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `person` VARCHAR(250) NOT NULL,
  `loan_date` DATE NOT NULL,
  `return_date` DATE NULL,
  `book_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_loans_book1_idx` (`book_id` ASC) VISIBLE,
  CONSTRAINT `fk_loans_book1`
    FOREIGN KEY (`book_id`)
    REFERENCES `mylibrary`.`book` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- Criando a tabela "wishlist"
CREATE TABLE IF NOT EXISTS `mylibrary`.`wishlist` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(250) NOT NULL,
  `author` VARCHAR(250) NOT NULL,
  `year` YEAR(4) NULL,
  `comments` VARCHAR(250) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
